name: job concurrency
on:
 workflow_dispatch:
jobs:
 test:
  concurrency: 
   group: ${{github.repository}}-${{github.ref}}
   cancel-in-progress: false  #Will not cancell the running job and wont trigger a new one.
  runs-on: ubuntu-latest
  steps:
  - name: sleep
    run: sleep 100
 
