name: job concurrency
on:
 workflow_dispatch:
jobs:
 test:
  concurrency: 
   group: ${{github.repository}}-${{github.ref}}
   cancel-in-progress: true  #Will cancell the running job and trigger a new one.
  runs-on: ubuntu-latest
  steps:
  - name: sleep
    run: sleep 100
 
