name: condition workflow
on:
 workflow_dispatch: 
jobs:
 conditions:
  runs-on: ubuntu-latest
  steps:
  - name: run when it is main
    if: github.ref == 'refs/heads/main'
    run: echo "${{github.ref}}"
  - name: run when it is not main
    if: github.ref == 'refs/heads/dev-*'
    run: echo "not main"
