name: inputs test
on: 
 workflow_dispatch:
   inputs:
     name:
      description: "Enter you name"
      required: false
      default: "DevOps engineer"
     env:
      description: "provide the environment"
      required: true
      type: choice
      default: dev
      options:
       - dev
       - prod
     retry_count:
      description: "number of retries"
      default: "3"
      required: false
jobs:
 provide_inputs:
  runs-on: ubuntu-latest
  steps:
  - name: print inputs
    run: |
     echo "${{github.event.inputs.name}}"
     echo "${{github.event.inputs.env}}"
     echo "${{github.event.inputs.retry_count}}"
