name: test
on:
 workflow_dispatch:
  inputs: #Inputs are at workflow trigger level
   name:
    description: "Enter your name"
    required: true
    default: "Chakradhar Reddy Jeereddy"
   env:
    description: "Enter the environment"
    required: true
    default: "dev"
    type: choice
    options:
      - dev
      - prod
   retry_count: 
     description: "Number of retries"
     required: false
     default: "3"
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
  - name: print name
    run: echo "hello world"
