name: test
on:
 workflow_dispatch:
env: 
 version: ${GITHUB_SHA::5}
jobs:
 test:
  timeout-minutes: 1
  concurrency:
   group:  ${{github.repository}}-${{github.ref}}
   cancel-in-progress: false
  runs-on: ubuntu-latest
  steps:
  - name: print version
    run: |
       echo "Version: ${version}"
