name: test
on:
 workflow_dispatch:
jobs:
 test:
  timeout-minutes: 1
  concurrency:
   group:  ${{github.repository}}-${{github.ref}}
   cancel-in-progress: false
  runs-on: ubuntu-latest
  steps:
  - name: get commitid
    run: |
       echo "version=${GITHUB_SHA::5}" >> "${GITHUB_ENV}"
       
  - name: Print version
    run: |
     echo "Version: ${version}"
