name: set timeout
on:
 workflow_dispatch: 
jobs:
 myworkflow:
  runs-on: ubuntu-latest
  timeout-minutes: 1
  steps:
  - name: Timeout if job runs beyond 1 minutes
    run: echo "job should not run beyond 1 minutes"
  - name: sleep for 10 minutes
    run: sleep 100
